import { notFound } from 'next/navigation';
import Link from 'next/link';
import { DocCodeBlock } from '@/components/docs/DocCodeBlock';
const guides = {
  introduction: { title:'Uma biblioteca para aprender', lead:'Componentes pedagógicos nascidos de cursos reais, organizados em React e TypeScript.', paragraphs:['Um banner apresenta o assunto. Uma citação abre espaço para refletir. Um acordeão aprofunda o conteúdo e uma questão permite praticar. A Modfly fornece essas peças; o curso fornece o conteúdo e a navegação.','O core @modfly/ui reúne componentes e estilos. @modfly/ui-avamec acrescenta atividades com persistência explícita. A CLI modfly permite copiar código editável.','Atomic Design organiza a implementação em átomos, moléculas, organismos e templates. Todos são importados pela API pública dos pacotes.'], code:"import { Citation } from '@modfly/ui';\nimport '@modfly/ui/styles.css';\n\nexport function Aula() {\n  return <Citation title=\"Para refletir\" text=\"Aprender exige prática.\" />;\n}" },
  installation: { title:'Sua primeira aula', lead:'Instale o pacote, importe os estilos e componha seu conteúdo.', paragraphs:['A versão 1.1.0 está em preparação; os comandos npm passam a funcionar após a publicação. Antes disso, use o monorepo ou os tarballs gerados por pnpm pack.','O consumidor precisa de React e React DOM 18.2 ou 19. O ambiente do monorepo e a CLI usam Node 22.14 ou superior.','Importe o CSS uma vez: src/main.tsx no Vite, app/layout.tsx no Next.js. Exemplos com callbacks devem ficar dentro de uma fronteira de cliente.'], code:"pnpm add @modfly/ui@1.1.0\n\n# No entrypoint global:\n# import '@modfly/ui/styles.css';" },
  'tailwind-setup': { title:'Estilos prontos para usar', lead:'O pacote distribui CSS compilado; Tailwind é opcional no consumidor.', paragraphs:['Importar @modfly/ui/styles.css é suficiente para carregar os utilitários utilizados pelos componentes. O arquivo não inclui o reset Preflight. Componentes estruturais também podem usar Emotion internamente.','Se você copia código pela CLI e cria novas classes Tailwind, configure o content para incluir o diretório copiado. O CSS distribuído só contém classes conhecidas da biblioteca.','Mantenha apenas uma estratégia para os mesmos utilitários: CSS distribuído ou compilação própria. Evite depender de classes geradas dinamicamente que não estejam presentes no content.'], code:"// tailwind.config.js — para código copiado e personalizado\nexport default {\n  content: ['./src/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],\n};\n\n// Ou use diretamente o CSS distribuído:\n// import '@modfly/ui/styles.css';" },
  theming: { title:'O conteúdo ganha sua identidade', lead:'Use variantes e propriedades de apresentação preservando legibilidade e interação.', paragraphs:['Não existe um provider universal de tema nesta versão. Cada componente expõe suas opções: variant, cores, dimensões e className quando disponíveis. Consulte a tabela da API antes de personalizar.','As ilustrações fazem parte da identidade dos cursos de origem. Fotos, textos e logos específicos devem ser fornecidos pelo curso. Algumas variantes usam cores fixas nos SVGs.','A documentação tem tokens próprios de cor e tipografia. Esses tokens não substituem automaticamente as cores dos componentes da biblioteca. Para alterações profundas, a CLI oferece código editável.'], code:"import { Citation } from '@modfly/ui';\n\nexport function Destaque() {\n  return <Citation variant=\"yellow\" title=\"Uma nova perspectiva\"\n    text=\"Explique a ideia com suas palavras.\" />;\n}" }
};
export function generateStaticParams() { return Object.keys(guides).map(slug => ({slug})); }
export default async function Page({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; if (!(slug in guides)) notFound(); const guide=guides[slug as keyof typeof guides];
  return <article className="doc-prose px-4 sm:px-8"><div className="doc-cat">Primeiros passos</div><h1 className="doc-title">{guide.title}<i>.</i></h1><p className="doc-lead">{guide.lead}</p>{guide.paragraphs.map(p=><p className="doc-p" key={p}>{p}</p>)}<DocCodeBlock filename="Exemplo" raw={guide.code}><pre>{guide.code}</pre></DocCodeBlock><h2 className="doc-h2">Continue explorando</h2><ul className="prose-ul"><li><Link href="/docs/components/citation">Experimentar Citation</Link></li><li><Link href="/docs/getting-started/avamec">Criar uma atividade AVAMEC</Link></li><li><Link href="/docs/getting-started/cli">Copiar código com a CLI</Link></li></ul></article>;
}
