import { type Locale } from '@/lib/i18n';
const descriptions: Record<string, [string, string]> = {
  variant: [
    'Apresentação visual; consulte as opções do tipo e as demonstrações.',
    'Visual presentation; see the type options and demonstrations.',
  ],
  colorScheme: ['Paleta visual do componente.', 'Component color palette.'],
  text: ['Texto principal do componente.', 'Main component text.'],
  textColor: ['Cor do texto.', 'Text color.'],
  textClassName: ['Classes CSS aplicadas ao texto.', 'CSS classes applied to text.'],
  href: ['Endereço de destino do link.', 'Link destination URL.'],
  onClick: [
    'Callback executado ao acionar o componente.',
    'Callback executed when the component is activated.',
  ],
  target: [
    'Contexto de navegação do link, como _blank.',
    'Link navigation context, such as _blank.',
  ],
  className: [
    'Classes CSS adicionais no elemento exposto pelo componente.',
    'Additional CSS classes on the element exposed by the component.',
  ],
  width: [
    'Largura; use o formato aceito pelo tipo.',
    'Width; use the format accepted by the type.',
  ],
  height: [
    'Altura; use o formato aceito pelo tipo.',
    'Height; use the format accepted by the type.',
  ],
  pdfile: ['Endereço do arquivo PDF.', 'PDF file URL.'],
  variation: [
    'Variação visual ou de conteúdo aceita pelo componente.',
    'Visual or content variation supported by the component.',
  ],
  isOpen: [
    'Estado de abertura controlado pela aplicação.',
    'Open state controlled by the application.',
  ],
  onToggle: [
    'Callback para atualizar o estado de abertura.',
    'Callback for updating the open state.',
  ],
  items: [
    'Itens na ordem de apresentação; veja os campos no tipo.',
    'Items in presentation order; see the type for fields.',
  ],
  numberOfItems: ['Quantidade configurada de itens.', 'Configured item count.'],
  title: ['Título apresentado no componente.', 'Title displayed in the component.'],
  children: [
    'Conteúdo React composto dentro do componente.',
    'React content composed inside the component.',
  ],
  link: ['Endereço do recurso associado.', 'Associated resource URL.'],
  linkLabel: ['Texto que identifica o destino do link.', 'Text identifying the link destination.'],
  src: ['Endereço principal da imagem ou mídia.', 'Primary image or media URL.'],
  fallback: [
    'Imagem alternativa usada após falha de carregamento.',
    'Alternative image used after a loading failure.',
  ],
  imgCenter: ['Centraliza a imagem na composição.', 'Centers the image in the composition.'],
  maxWidth: ['Limite de largura do conteúdo.', 'Content maximum width.'],
  alt: [
    'Descrição textual da imagem; use vazio apenas para decoração.',
    'Text description of the image; use an empty value only for decoration.',
  ],
  onRetry: [
    'Callback responsável pela tentativa de recuperação.',
    'Callback responsible for a recovery attempt.',
  ],
  style: ['Estilos inline aceitos pelo elemento.', 'Inline styles accepted by the element.'],
  bgColor: ['Cor de fundo.', 'Background color.'],
  isCustomContent: [
    'Ativa a apresentação de conteúdo personalizado.',
    'Enables custom content presentation.',
  ],
  content: [
    'Conteúdo exibido; confira no tipo se aceita texto, HTML ou ReactNode.',
    'Displayed content; check the type for text, HTML or ReactNode support.',
  ],
  position: ['Posição do elemento na composição.', 'Element position in the composition.'],
  widthMobile: [
    'Largura aplicada na apresentação móvel.',
    'Width used in the mobile presentation.',
  ],
  reference: ['Atribuição ou referência do conteúdo.', 'Content attribution or reference.'],
  cardFlipData: [
    'Dados da frente e do verso dos cartões.',
    'Data for card fronts and reverse sides.',
  ],
  cardsData: [
    'Dados de imagem, título e conteúdo dos cartões.',
    'Card image, title and content data.',
  ],
  topBgImg: ['Imagem decorativa do topo.', 'Top decorative image.'],
  iconImg: ['Imagem usada como ícone.', 'Image used as an icon.'],
  bottomBgImg: ['Imagem decorativa da base.', 'Bottom decorative image.'],
  bottomBgWidth: ['Largura da decoração inferior.', 'Bottom decoration width.'],
  bottomBgHeight: ['Altura da decoração inferior.', 'Bottom decoration height.'],
  isVimeo: ['Seleciona o comportamento específico de Vimeo.', 'Selects Vimeo-specific behavior.'],
  isOnlyText: ['Seleciona a apresentação apenas textual.', 'Selects the text-only presentation.'],
  isReels: [
    'Seleciona a apresentação de vídeo vertical.',
    'Selects the vertical video presentation.',
  ],
  widthTablet: [
    'Largura usada na apresentação de tablet.',
    'Width used in the tablet presentation.',
  ],
  containerClassName: ['Classes CSS do contêiner.', 'Container CSS classes.'],
  imgSrc: ['Endereço da imagem principal.', 'Main image URL.'],
  imgFb: ['Endereço da imagem alternativa.', 'Fallback image URL.'],
  imgSrcMobile: [
    'Endereço da imagem específica para telas pequenas.',
    'Image URL specifically for small screens.',
  ],
  type: [
    'Tipo de apresentação entre as opções declaradas.',
    'Presentation type from the declared options.',
  ],
  number: ['Número associado ao conteúdo.', 'Number associated with the content.'],
  caption: ['Legenda da imagem.', 'Image caption.'],
  smallFont: ['Ativa a opção de fonte menor.', 'Enables the smaller font option.'],
  borderColor: ['Cor da borda.', 'Border color.'],
  backgroundColor: ['Cor de fundo.', 'Background color.'],
  option: [
    'Opção de composição visual aceita pelo componente.',
    'Visual composition option supported by the component.',
  ],
  imageSrc: ['Endereço da imagem.', 'Image URL.'],
  align: ['Alinhamento do conteúdo.', 'Content alignment.'],
  subtitle: ['Subtítulo de apoio.', 'Supporting subtitle.'],
  textList: ['Textos que formam a lista.', 'Texts making up the list.'],
  specText: ['Trecho de texto destacado.', 'Highlighted text excerpt.'],
  quoteAlign: ['Alinhamento da citação.', 'Quotation alignment.'],
  fullScreen: ['Ativa a apresentação em tela cheia.', 'Enables full-screen presentation.'],
  titleColor: ['Cor do título principal.', 'Main title color.'],
  titleColor2: [
    'Cor alternativa do título conforme o estado visual.',
    'Alternative title color according to visual state.',
  ],
  bgInsideColor: ['Cor do fundo interno.', 'Inner background color.'],
  iconBackColor: ['Cor do fundo do ícone.', 'Icon background color.'],
  upArrowColorVariant: ['Variante de cor da seta para cima.', 'Up-arrow color variant.'],
  downArrowColorVariant: ['Variante de cor da seta para baixo.', 'Down-arrow color variant.'],
  headerHeight: ['Altura do cabeçalho.', 'Header height.'],
  sidePadding: ['Espaçamento interno lateral.', 'Horizontal inner spacing.'],
  course: [
    'Identificador visual de curso aceito pelo componente.',
    'Course visual identifier supported by the component.',
  ],
  text1: ['Texto do primeiro grupo.', 'First group text.'],
  text11: ['Texto complementar do primeiro grupo.', 'First group supporting text.'],
  text2: ['Texto do segundo grupo.', 'Second group text.'],
  text22: ['Texto complementar do segundo grupo.', 'Second group supporting text.'],
  text3: ['Texto do terceiro grupo.', 'Third group text.'],
  text33: ['Texto complementar do terceiro grupo.', 'Third group supporting text.'],
  text333: ['Texto adicional do terceiro grupo.', 'Third group additional text.'],
  lineColor: ['Cor da linha de conexão.', 'Connecting line color.'],
  questionNumber: ['Número exibido junto ao enunciado.', 'Number displayed with the question.'],
  answersContent: [
    'Conteúdo das alternativas apresentadas.',
    'Content of the displayed alternatives.',
  ],
  groupIndex: ['Índice do grupo na composição.', 'Group index in the composition.'],
  dotColor: ['Cor dos marcadores.', 'Marker color.'],
  bgImages: ['Imagens de fundo na ordem dos slides.', 'Background images in slide order.'],
  bgPosition: ['Posicionamento da imagem de fundo.', 'Background image position.'],
  word: ['Termo que abre a definição.', 'Term that opens the definition.'],
  definition: ['Definição associada ao termo.', 'Definition associated with the term.'],
  hasBoldTitle: ['Aplica destaque em negrito ao título.', 'Applies bold emphasis to the title.'],
  fontColor: ['Cor da fonte.', 'Font color.'],
  mobileWidth: ['Largura na apresentação móvel.', 'Width in the mobile presentation.'],
  tabletHeight: ['Altura na apresentação de tablet.', 'Height in the tablet presentation.'],
  mobileHeight: ['Altura na apresentação móvel.', 'Height in the mobile presentation.'],
  numberOfPages: ['Quantidade total de páginas.', 'Total page count.'],
  currentPage: [
    'Página atual, controlada pela aplicação e numerada a partir de 1.',
    'Current page, controlled by the application and numbered from 1.',
  ],
  onPageChange: [
    'Callback que recebe a página selecionada.',
    'Callback receiving the selected page.',
  ],
  onNext: ['Callback de avanço de página.', 'Next-page callback.'],
  onPrev: ['Callback de retorno de página.', 'Previous-page callback.'],
  showNumbers: ['Exibe os números de página.', 'Displays page numbers.'],
  bulletColor: ['Cor dos indicadores inativos.', 'Inactive indicator color.'],
  bulletActiveColor: ['Cor do indicador ativo.', 'Active indicator color.'],
  onSlideChange: ['Callback que recebe a mudança de slide.', 'Callback receiving slide changes.'],
  hasTitle: ['Controla a exibição do título.', 'Controls title visibility.'],
  imgSrc2: ['Endereço da segunda imagem.', 'Second image URL.'],
  imgMaxWidth: ['Limite de largura das imagens.', 'Image maximum width.'],
  isReverse: [
    'Inverte a disposição visual entre texto e imagem.',
    'Reverses the visual arrangement of text and image.',
  ],
  justifyText: ['Ativa o alinhamento justificado do texto.', 'Enables justified text alignment.'],
  module: [
    'Número do módulo usado para selecionar a ilustração.',
    'Module number used to select the illustration.',
  ],
};
export function propDescription(name: string, lang: Locale) {
  const entry = descriptions[name];
  if (!entry) throw new Error(`Missing property documentation: ${name}`);
  return entry[lang === 'pt' ? 0 : 1];
}
